name: "[Manual] GitHub Release"

on:
  workflow_dispatch:

jobs:
  github-release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: "11"

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

    - name: sbt GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
      run: |
        echo "Run] sbt GitHub release"
        export SOURCE_DATE_EPOCH=$(date +%s)
        echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
        echo "====================="
        echo 'sbt -J-Xmx2048m devOopsGitHubRelease'
        sbt \
          -J-Xmx2048m \
          devOopsGitHubRelease
